// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO "user" (Firstname, LastName, Biography)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Firstname string
	Lastname  string
	Biography string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Firstname, arg.Lastname, arg.Biography)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM "user"
WHERE ID = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, firstname, lastname, biography
FROM "user"
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Biography,
	)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT id, firstname, lastname, biography
FROM "user"
ORDER BY Firstname
`

func (q *Queries) ListUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Biography,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByName = `-- name: SearchByName :one
SELECT id, firstname, lastname, biography
FROM "user"
WHERE Firstname = $1
`

func (q *Queries) SearchByName(ctx context.Context, firstname string) (User, error) {
	row := q.db.QueryRowContext(ctx, searchByName, firstname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Biography,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "user"
SET Firstname = $1,
    LastName  = $2,
    Biography = $3
WHERE ID = $4
`

type UpdateUserParams struct {
	Firstname string
	Lastname  string
	Biography string
	ID        int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Firstname,
		arg.Lastname,
		arg.Biography,
		arg.ID,
	)
	return err
}
